# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

display_url: https://spacialstudio.netlify.com # This url will display in the top-right of the CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Url, name: siteUrl, widget: string, required: false}
          - {label: Site Description, name: siteDescription, widget: text, required: false}
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - {label: Image, name: image, widget: image, required: false}
              - {label: Twitter Site Account, name: twitterSiteAccount, widget: string, required: false}
              - {label: Twitter Creator Account, name: twitterCreatorAccount, widget: string, required: false}
          - label: Location
            name: location
            widget: object
            fields:
              - {label: Latitude, name: lat, widget: number, required: false}
              - {label: Longitude, name: lng, widget: number, required: false}
          - {label: Office Address, name: officeAddress, widget: text, required: false}
          - {label: Postal Address, name: postalAddress, widget: text, required: false}
          - {label: Phone, name: phone, widget: string, required: false}
          - {label: Email, name: email, widget: string, required: false, pattern: ['^([A-Z|a-z|0-9](\.|_){0,1})+[A-Z|a-z|0-9]\@([A-Z|a-z|0-9])+((\.){0,1}[A-Z|a-z|0-9]){2}\.[a-z]{2,3}$', 'Email address required']}
          - {label: Header Meta / Scripts, name: headerScripts, widget: text, required: false}
          - {label: Enable Service Worker Pre-Cache, name: enableServiceWorker, widget: boolean, required: false}
  - name: "pages"
    label: "Pages"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/pages/contact.md"
        label: "Contact Page"
        name: "contact-page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Meassage, name: latlong, widget: message}
      - file: "content/pages/blog.md"
        label: "Blog Page"
        name: "blog-page"
        fields:
          - {label: Title, name: title, widget: string}
      - file: "content/pages/project.md"
        label: "Project Page"
        name: "project-page"
        fields:
          - {label: Title, name: title, widget: string}
      - file: "content/pages/services.md"
        label: "Services Page"
        name: "services-page"
        fields:
          - {label: Title, name: title, widget: string}
          - label: "Gallery Images"
            name: "galleryImages"
            widget: "list"
            fields:
              - {label: Image, name: galleryimage, widget: image}
          - {label: Gallery Title, name: galleryTitle, widget: string}
          - {label: Gallery Description, name: galleryDescription, widget: markdown}
          - {label: Three Column Section Title, name: threeColumnSectionTitle, widget: string}
          - {label: Three Column Section, name: threeColumnSection, widget: markdown}
          - label: "Accordion"
            name: "accordion"
            widget: "list"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Description, name: description, widget: markdown}
              - {label: Link Title, name: linkTitle, widget: string}
              - {label: Link, name: link, widget: file}
          - {label: Project Section Title, name: projectSectionTitle, widget: string}
          # - label: "Featured Projects"
          #   name: "featuredProject"
          #   widget: "list"
          #   fields:
          #     - label: "Project List"
          #       name: "projectList"
          #       widget: "relation"
          #       collection: "projects"
          #       searchFields: ["name"]
          #       valueField: "name"
          - {label: News Section Title, name: newsSectionTitle, widget: string}
            # - label: "Featured Projects"
            #   name: "featuredProject"
            #   widget: "list"
            #   fields:
            #     - label: "Project List"
            #       name: "projectList"
            #       widget: "relation"
            #       collection: "projects"
            #       searchFields: ["name"]
            #       valueField: "name"
          - {label:  Booking Title, name: bookingTitle, widget: string}
      - file: "content/pages/about.md"
        label: "About Page"
        name: "about-page"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Featured Image, name: featuredImage, widget: image}
          - {label: Welcome Quote, name: welcomeQuote, widget: text}
          - {label: Welcome Section, name: welcomeSection, widget: markdown}
          - {label: History Title, name: historyTitle, widget: string}
          - {label: History Section, name: historySection, widget: markdown}
          - {label: Services Title, name: servicesTitle, widget: string}
          - label: Service
            name: service
            widget: list
            fields:
              - { label: Title, name: title, widget: string}
              - { label: Icon, name: icon, widget: image}
              - { label: Description, name: description, widget: text}
      - file: "content/pages/home.md"
        label: "Home Page"
        name: "home-page"
        fields:
          - label: "Welcome Gallery Images"
            name: "welcomeGalleryImages"
            widget: "list"
            fields:
              - {label: Image, name: galleryimage, widget: image}
          - {label: Title, name: title, widget: string}
          - label: Service
            name: service
            widget: list
            fields:
              - { label: Title, name: title, widget: string}
              - { label: Icon, name: icon, widget: image}
              - { label: Description, name: description, widget: text}
          - {label: About Image, name: aboutImage, widget: image}
          - {label: About Section Title, name: aboutSectionTitle, widget: string}
          - {label: About Content, name: aboutContent, widget: markdown}
          - {label: About link text, name: aboutLinkText, widget: string}
          - {label: News Section Title, name: newsSectionTitle, widget: string}
          - {label: News Content, name: newsContent, widget: markdown}
          - {label: News link text, name: newsLinkText, widget: string}
          - {label: Project Section Title, name: projectSectionTitle, widget: string}
          - {label: Testimonial Section Title, name: testimonialSectionTitle, widget: string}
  - name: staff
    label: Staff
    editor:
      preview: false
    folder: content/staff
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string}
      - {label: Subtitle, name: subtitle, widget: string}
      - {label: Image, name: image, widget: image}
      - {label: Content, name: body, widget: markdown}
      - {label: Instagram, name: instagram, widget: string, required: false}
      - {label: Twitter, name: twitter, widget: string, required: false}
      - {label: Linked In, name: linkedin, widget: string, required: false}
      - {label: Order, name: order, widget: number, required: false}
  - name: projects
    label: Projects
    editor:
      preview: false
    folder: content/projects
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Project Featured Image, name: projectFeaturedImage, widget: image}
      - {label: Title, name: title, widget: string}
      - {label: Year, name: year, widget: number, required: false}
      - {label: Type Of Project, name: typeofproject, widget: string, required: false}
      - {label: Client, name: client, widget: string, required: false}
      - {label: Order, name: order, widget: number}
      - {label: Content, name: body, widget: markdown}
      - {label: Testimonial, name: testimonial, widget: markdown, required: false }
      - {label: Name, name: name, widget: string, required: false}
      - {label: Role, name: role, widget: string, required: false}
      - label: "Project Gallery Images"
        name: "projectGalleryImages"
        widget: "list"
        fields:
          - {label: Image, name: galleryimage, widget: image}
  - name: posts
    label: Posts
    editor:
      preview: false
    folder: content/posts
    slug: "{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: Title, name: title, widget: string}
      - label: 'Status'
        name: 'status'
        widget: 'select'
        options: ["Published", "Featured / Published", "Draft / Hidden"]
        default: 'Published'
      - {label: Date / Order, name: date, widget: date}
      - {label: Category, name: category, widget: string}
      - {label: Post Featured Image, name: postFeaturedImage, widget: image}
      - {label: Excerpt, name: excerpt, widget: text}
      - {label: Content, name: body, widget: markdown}
      - label: "Gallery Images"
        name: "galleryImages"
        widget: "list"
        fields:
          - {label: Image, name: galleryimage, widget: image}
        required: false
